services:
  - type: web
    name: bronx-site
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: site
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /avatar.png
        name: Cache-Control
        value: public, max-age=3600
      - path: /fonts/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /style.css
        name: Cache-Control
        value: public, max-age=3600
      - path: /script.js
        name: Cache-Control
        value: public, max-age=3600
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
